/**
 * State Module Barrel Exports
 *
 * Re-exports all state management modules from a single entry point.
 */

// Scene state
export {
  scene,
  layers,
  results,
  probeResults,
  probePending,
  receiverEnergyTotals,
  panelEnergyTotals,
  collapsedSources,
  getSourceSeq,
  setSourceSeq,
  nextSourceId,
  getReceiverSeq,
  setReceiverSeq,
  nextReceiverId,
  getPanelSeq,
  setPanelSeq,
  nextPanelId,
  getProbeSeq,
  setProbeSeq,
  nextProbeId,
  getBuildingSeq,
  setBuildingSeq,
  nextBuildingId,
  getBarrierSeq,
  setBarrierSeq,
  nextBarrierId,
  getSoloSourceId,
  setSoloSourceId,
  findSource,
  findReceiver,
  findPanel,
  findProbe,
  findBuilding,
  findBarrier,
  getEnabledSources,
} from './scene.js';

// Selection state
export {
  type PinnedContextPanel,
  type PinnedProbePanel,
  type ProbeSnapshot,
  getSelection,
  setSelectionState,
  getHoverSelection,
  setHoverSelection,
  getActiveProbeId,
  setActiveProbeId,
  clearSelection,
  getPinnedContextPanels,
  addPinnedContextPanel,
  removePinnedContextPanel,
  getNextPinnedContextId,
  getNextInspectorZIndex,
  bringToFront,
  getPinnedProbePanels,
  getPinnedProbePanel,
  setPinnedProbePanel,
  removePinnedProbePanel,
  getProbeSnapshots,
  addProbeSnapshot,
  removeProbeSnapshot,
  getNextProbeSnapshotId,
  isSelected,
  hasSelection,
  getSingleSelectedId,
} from './selection.js';

// History state
export {
  type SceneSnapshot,
  getHistory,
  setHistory,
  getHistoryIndex,
  setHistoryIndex,
  getIsDirty,
  setIsDirty,
  canUndo,
  canRedo,
  getHistoryLength,
  pushSnapshot,
  getSnapshot,
  stepBack,
  stepForward,
  clearHistory,
  markDirty,
  markSaved,
} from './history.js';

// Tools state
export {
  type BuildingDrawingMode,
  type BarrierDrawingMode,
  type BarrierDraft,
  type BuildingDraft,
  type BuildingCenterDraft,
  type BarrierCenterDraft,
  getActiveTool,
  setActiveTool,
  getBuildingDrawingMode,
  setBuildingDrawingMode,
  getBarrierDrawingMode,
  setBarrierDrawingMode,
  getDragState,
  setDragState,
  getDragContribution,
  setDragContribution,
  isDragDirty,
  setDragDirty,
  clearDragState,
  getMeasureStart,
  setMeasureStart,
  getMeasureEnd,
  setMeasureEnd,
  isMeasureLocked,
  setMeasureLocked,
  clearMeasure,
  getBarrierDraft,
  setBarrierDraft,
  isBarrierDraftAnchored,
  setBarrierDraftAnchored,
  isBarrierDragActive,
  setBarrierDragActive,
  getBarrierCenterDraft,
  setBarrierCenterDraft,
  clearBarrierDraft,
  getBuildingDraft,
  setBuildingDraft,
  isBuildingDraftAnchored,
  setBuildingDraftAnchored,
  isBuildingDragActive,
  setBuildingDragActive,
  getBuildingCenterDraft,
  setBuildingCenterDraft,
  getBuildingPolygonDraft,
  setBuildingPolygonDraft,
  addBuildingPolygonPoint,
  getBuildingPolygonPreviewPoint,
  setBuildingPolygonPreviewPoint,
  clearBuildingDraft,
  clearAllDrafts,
  isDrawing,
} from './tools.js';

// Viewport state
export {
  setCanvasRef,
  getCanvasRef,
  getBasePixelsPerMeter,
  setBasePixelsPerMeter,
  getZoom,
  setZoom,
  getPixelsPerMeter,
  getPanOffset,
  setPanOffset,
  getPanState,
  setPanState,
  getSnapMeters,
  isInteractionActive,
  setInteractionActive,
  worldToCanvas,
  canvasToWorld,
  getVisibleBounds,
  getCanvasDimensions,
  snapToGrid,
  isNearGrid,
  zoomAtPoint,
  resetViewport,
} from './viewport.js';
